const curatedViews = {
    // These are identifiers to enable industry or company-specific customization for the initial articles shown on the website.
    // Example key decoding: 'view-a8b3' -> Google, 'view-c4d7' -> E-Commerce
    'view-a8b3': [
        'api-banking-overview-aug-2019',
        'visa-combatting-fraud-news-jun-2019',
        'fintech-bank-collaboration-jun-2023',
        'big-tech-is-coming-dec-2019',
        'connected-intelligence-fighting-fraud-july-2019',
        'core-modernization-cloud-migration-banks-oct-2022'
    ],
    'view-c4d7': [
        'big-tech-is-coming-dec-2019',
        'improving-customer-experience-oct-2019',
        'consumer-covid-response-news-mar-2020',
        'fintech-bank-collaboration-jun-2023',
        'nonfinancial-brands-embedded-finance-april-2023',
        'cyber-attack-architecture-nudata-jan-2020'
    ]
};

const articles = [
            {
                id: 'api-banking-overview-aug-2019',
                title: 'What Are APIs and How Are They Changing Banking?',
                publication: 'PaymentsJournal Article',
                genre: 'News & Analysis',
                date: '2019-08-13',
                summary: "Explains how Application Programming Interfaces (APIs) are driving the banking industry's shift to digital-first models. It covers how APIs enable open banking, foster innovation through collaboration between banks and FinTechs, and streamline payments and other banking operations.",
                article_url: 'https://www.paymentsjournal.com/what-are-apis-and-how-are-they-changing-banking/',
                tags: ['Digital Payments', 'Customer Experience', 'Payments Innovation','Mobile Banking', 'Emerging Technology'],
            },
            {
                id: 'visa-mastercard-dispute-explainer-nov-2019',
                title: 'Visa and Mastercard Changed Their Dispute Resolution Process. Here’s What You Need to Know',
                publication: 'PaymentsJournal Article',
                genre: 'News & Analysis',
                date: '2019-11-13',
                summary: 'An overview of Visa and Mastercard’s dispute resolution changes, including Visa Claims Resolution (VCR) and Mastercard Dispute Resolution Initiative (MDRI), and their impact on merchants and consumers.',
                article_url: 'https://www.paymentsjournal.com/visa-and-mastercard-changed-their-dispute-resolution-process-heres-what-you-need-to-know/',
                tags: ['Rules & Regulations', 'Credit Cards'],
            },
            {
                id: 'fed-real-time-payment-announcement-news-aug-2019',
                title: 'Fed to Create Real-Time Payments Network',
                publication: 'PaymentsJournal Article',
                genre: 'News & Analysis',
                date: '2019-08-05',
                summary: 'An overview of the Federal Reserve’s decision to build FedNow, a real-time payments network, and its implications for the U.S. payments landscape. It covers the Fed\'s speech announcing the roll-out and includes expert analysis from a Mercator senior analyst.',
                article_url: 'https://www.paymentsjournal.com/fed-to-create-real-time-payment-network/',
                tags: ['Payments Innovation', 'Emerging Technology'],
            },
            {
                id: 'visa-combatting-fraud-news-jun-2019',
                title: 'Using Artificial Intelligence, Visa Is Combatting Fraud at Nearly the Speed of Light',
                publication: 'PaymentsJournal Article',
                genre: 'News & Analysis',
                date: '2019-06-17',
                summary: "Explains how Visa’s AI-powered system, Visa Advanced Authorization (VAA), reviews every transaction on VisaNet in about one millisecond—analyzing over 500 risk signals to differentiate fraud from good behavior. This ultra-fast risk scoring helps issuers stop roughly $25 billion in fraud annually without slowing down customers or triggering false declines..",
                article_url: 'https://www.paymentsjournal.com/using-artificial-intelligence-visa-is-combatting-fraud-at-nearly-the-speed-of-light/',
                tags: ['Fraud Prevention/Detection', 'Artificial Intelligence', 'Cybersecurity', 'Emerging Technology'],
            },

            {
                id: 'fintech-bubble-profitability-mar-2023',
                title: 'The Bursting FinTech Bubble Places Primacy on Profitability',
                publication: 'PYMNTS-Sezzle FinTech Tracker',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'An analysis of the significant shift in the FinTech landscape, where economic headwinds and market corrections are forcing companies, especially in the BNPL sector, to move beyond growth-at-all-costs and focus intensely on achieving sustainable profitability.',
                tags: ['FinTech', 'Traditional & Alternative Credit'],
            },
            {
                id: 'verify-account-identity-nov-2019',
                title: 'Verifying Account Identity in the Age of Real-Time Payments',
                publication: 'PaymentsJournal-GIACT Advertorial',
                genre: 'Advertorials',
                date: '2019-10-02',
                summary: 'Explores the critical need for robust account verification in the era of real-time payments. It covers various methods, from traditional pre-notification and trial deposits to advanced multi-layered identity verification solutions, to help merchants prevent fraud and costly errors.',
                article_url: 'https://www.paymentsjournal.com/verifying-account-identity-in-the-age-of-real-time-payments/',
                tags: ['Fraud Prevention/Detection', 'Cybersecurity', 'Artificial Intelligence', 'Emerging Technology'],
            },
            {
                id: 'fintech-bank-collaboration-jun-2023',
                title: 'The FinTech-Bank Relationship Shifts Toward Collaboration',
                publication: 'PYMNTS-Sezzle FinTech Tracker',
                genre: 'Advertorials',
                date: '2023-06-01',
                summary: 'Examines the evolving dynamic between traditional financial institutions and FinTechs, highlighting a strategic move from competition to collaboration. This shift is driven by digital transformation, open banking regulations, and shared security concerns.',
                tags: ['FinTech', 'Mobile Banking', 'Embedded Finance & BaaS', 'Emerging Technology'],
            },
            {
                id: 'credit-book-report-mercator-research-mar-2021',
                title: 'The 2021 Credit Card Data Book Part One: Internal Dynamics',
                publication: 'Mercator Advisory Group Paid Research',
                genre: 'Research',
                date: '2021-03-30',
                summary: 'This report provides a comprehensive, data-driven look the pandemic\'s impact on the credit industry for companies subscribed to Mercator\'s credit practice. It examines trends around credit card profitability, consumer interest in credit, and lender attitudes on credit policy.',
                tags: ['Credit Cards', 'Traditional & Alternative Credit', 'Banks & Traditional FIs', 'Consumer Behavior'],
            },
            {
                id: 'fintech-lending-access-may-2023',
                title: "FinTechs' Role in Improving Access to Lending Services",
                publication: 'PYMNTS-Sezzle FinTech Tracker',
                genre: 'Advertorials',
                date: '2023-05-01',
                summary: 'Explores how FinTech innovations and alternative credit models, such as BNPL, are providing crucial access to lending services for consumers who may be underserved by traditional credit scoring systems, thereby promoting financial inclusion.',
                tags: ['FinTech', 'Traditional & Alternative Credit'],
            },
            {
                id: 'restaurants-technology-inflation-mar-2023',
                title: 'Inflation Puts Technology on the Menu for Restaurants',
                publication: 'PYMNTS-Ingo Money Money Mobility Tracker',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'Investigates how soaring inflation and labor shortages are forcing restaurants to accelerate their adoption of technology. From AI-powered drive-thrus and robotic automation to digital ordering and personalized loyalty programs, technology is no longer a luxury but a critical tool for survival and growth in a challenging economic climate.',
                tags: ['Industry-Specific Payment Solutions', 'Digital Payments', 'Emerging Technology'],
            },
            {
                id: 'consumer-covid-response-news-mar-2020',
                title: 'Here’s How Consumers are Responding to COVID-19',
                publication: 'PaymentsJournal Article',
                genre: 'News & Analysis',
                date: '2020-03-31',
                summary: 'Shares early research on how the pandemic reshaped consumer habits, from increased online grocery shopping and food delivery to greater use of contactless payments. Highlights lasting shifts toward digital convenience as businesses adjusted to closures, service cuts, and staff reductions.',
                article_url: 'https://www.paymentsjournal.com/heres-how-consumers-are-responding-to-covid-19/',
                tags: ['Consumer Behavior', 'Customer Experience', 'Digital Payments', 'Emerging Technology']
            },
            {
                id: 'beauty-wellness-transformation-may-2023',
                title: 'The Digital Transformation of Beauty and Wellness Services',
                publication: 'PYMNTS-American Express B2B and Digital Payments Tracker',
                genre: 'Advertorials',
                date: '2023-05-01',
                summary: 'Analyzes the rapid adoption of digital tools within the beauty and wellness industry, from online booking and integrated payment systems to "treat now, pay later" financing, showcasing a sector-wide move towards a seamless, tech-driven customer experience.',
                tags: ['SMB', 'Customer Experience', 'Emerging Technology','Industry-Specific Payment Solutions'],
            },
            {
                id: 'smb-fraud-threats-remote-work-mar-2023',
                title: 'How SMBs Can Fight the Fraud Threats of Remote Work',
                publication: 'PYMNTS-American Express B2B and Digital Payments Tracker',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'An exploration of the heightened fraud and security risks for SMBs due to the rise of remote work. It focuses on payment fraud, business email compromise (BEC), and actionable strategies for defense in a decentralized work environment.',
                tags: ['SMB', 'Fraud Prevention/Detection', 'Cybersecurity', 'B2B'],
            },
            {
                id: 'b2b-e-commerce-marketplaces-report-mar-2021',
                title: 'B2B E-Commerce: The Challenges and Opportunities Caused by Digital Acceleration',
                publication: 'Mercator Advisory Group\'s Paid Research',
                genre: 'Research',
                date: '2021-03-26',
                summary: 'This report examines the rise of B2B marketplaces during the COVID era. It unpacks how the digital transformation of business has accelerated, why B2B marketplaces are popular, and the overall market size of this vertical.',
                tags: ['B2B', 'E-Commerce', 'Consumer Behavior', 'Digital Payments'],
            },
            {
                id: 'healthcare-payments-improvements-jun-2023',
                title: 'The Healthcare Industry Needs a Dose of Money Mobility',
                publication: 'PYMNTS-Ingo Money Money Mobility Tracker',
                genre: 'Advertorials',
                date: '2023-06-15',
                summary: 'Highlights the significant friction in the healthcare payments system, where a reliance on manual processes and paper-based billing creates confusion and delays for patients. It explores how the adoption of digital platforms and real-time payments can improve the patient experience, reduce costs for providers, and increase overall satisfaction.',
                tags: ['Industry-Specific Payment Solutions', 'Back-Office Solutions', 'Digital Payments', 'Consumer Behavior'],
            },
            {
                id: 'smb-retail-payments-jan-2023',
                title: 'Tapping The Payments Opportunity In SMB Retail',
                publication: 'PYMNTS-American Express B2B and Digital Payments Tracker',
                genre: 'Advertorials',
                date: '2023-01-01',
                summary: 'Highlights the significant opportunity for small and mid-sized retailers to drive growth and customer loyalty by adopting modern, flexible payment options that meet evolving consumer preferences for digital and contactless transactions.',
                tags: ['SMB', 'Retail', 'Digital Payments'],
            },
            {
                id: 'smb-cash-flow-2023-nov-dec-2022',
                title: "Improving SMBs' Cash Flow Management In 2023",
                publication: 'PYMNTS-American ExpressB2B and Digital Payments Tracker',
                genre: 'Advertorials',
                date: '2022-11-15',
                summary: 'A forward-looking piece on the critical nature of cash flow management for SMBs entering 2023. It discusses how technology and strategic partnerships can help businesses navigate economic uncertainty and late payment challenges.',
                tags: ['SMB', 'B2B', 'Back-Office Solutions', 'Emerging Technology'],
            },
             {
                id: 'nonfinancial-brands-embedded-finance-april-2023',
                title: 'How Nonfinancial Brands Can Benefit From Embedded Finance',
                publication: 'PYMNTS-Galileo Embedded Finance Tracker',
                genre: 'Advertorials',
                date: '2023-04-01',
                summary: 'Examines how nonfinancial brands are leveraging embedded finance and Banking as a Service (BaaS) to offer financial products like BNPL, branded debit cards, and in-app payments. This strategy helps them increase customer engagement, open new revenue streams, and strengthen their competitive edge.',
                tags: ['SMB', 'B2B', 'Emerging Technology', 'Embedded Finance & BaaS'],
            },
            {
                id: 'big-tech-is-coming-dec-2019',
                title: 'Hey Issuers, Big Tech Is Coming. Here’s How to Compete',
                publication: 'PaymentsJournal-OnDot Advertorial',
                genre: 'Advertorials',
                date: '2019-12-04',
                summary: 'Explores how Apple’s launch of the Apple Card—with its slick app, seamless onboarding, no fees, and ecosystem-driven rewards—is pushing traditional card issuers to rethink their strategies by focusing squarely on superior customer experience and digital-first design.',
                article_url: 'https://www.paymentsjournal.com/hey-issuers-big-tech-is-coming-heres-how-to-compete/',
                tags: ['FinTech', 'Mobile Banking', 'Consumer Behavior', 'Payments Innovation'],
            },
            {
                id: 'improving-customer-experience-oct-2019',
                title: 'Improving Customer Experience in the Moments That Matter',
                publication: 'PaymentsJournal-OnDot Advertorial',
                genre: 'Advertorials',
                date: '2019-10-22',
                summary: 'Highlights how financial institutions can seize high-stress customer touchpoints—like lost or compromised cards—to strengthen loyalty. Featuring insights from Mercator Advisory Group, the piece shows how mobile apps can streamline card shutdowns, real-time charge tracking, and clear alerts.',
                article_url: 'https://www.paymentsjournal.com/improving-customer-experience-in-the-moments-that-matter/',
                tags: ['FinTech', 'Customer Experience', 'Consumer Behavior', 'Mobile Banking'],
            },
            {
                id: 'connected-intelligence-fighting-fraud-july-2019',
                title: 'Connected Intelligence: A Holistic Approach to Fighting Fraud',
                publication: 'PaymentsJournal',
                genre: 'Advertorials',
                date: '2019-07-18',
                summary: "This outlines Mastercard's cutting-edge methods for fighting fraud by ditching passwords-only security in favor of real-time, layered authentication. It weaves together biometrics, device fingerprinting, behavioral profiling, location, and machine learning across the entire user journey. This lets companies flag fraudulent activity pre-transaction, minimize friction through smarter risk scoring, and reduce false positives while stopping fraud before it begins.",
                article_url: 'https://www.paymentsjournal.com/connected-intelligence-a-holistic-approach-to-fighting-fraud/',
                tags: ['Fraud Prevention/Detection', 'Artificial Intelligence', 'Cybersecurity', 'Emerging Technology'],
            },
            {
                id: 'understanding-synthetic-identity-fraud-aug-2019',
                title: 'Understanding and Stopping Synthetic Identity Fraud',
                publication: 'PaymentsJournal-PSCU Advertorial',
                genre: 'Advertorials',
                date: '2019-08-01',
                summary: 'Explains how fraudsters create synthetic identities by combining real and fake information to defraud banks and lenders, and explores the technologies and strategies companies can use to detect and prevent this type of fraud.',
                article_url: 'https://www.paymentsjournal.com/understanding-and-stopping-synthetic-identity-fraud/',
                tags: ['Fraud Prevention/Detection', 'Cybersecurity', 'Artificial Intelligence', 'Emerging Technology'],
            },
            {
                id: '3-payments-trends-dec-2019',
                title: '3 Payments Trends to Keep Track of in 2020',
                publication: 'PaymentsJournal Article',
                genre: 'News & Analysis',
                date: '2019-12-31',
                summary: 'A forward-looking analysis of the key payments trends poised to shape 2020. The article identifies three major shifts: the rise of real-time payments, the increasing importance of data-driven fraud prevention, and the growing consumer demand for seamless, integrated payment experiences across all channels.',
                article_url: 'https://www.paymentsjournal.com/3-payments-trends-to-keep-track-of-in-2020/',
                tags: ['Retail', 'Fraud Prevention/Detection', 'Emerging Technology'],
            },
            {
                id: 'cyber-attack-architecture-nudata-jan-2020',
                title: 'The Architecture of an Attack: NuData Breaks Down Account Takeover Attacks',
                publication: 'PaymentsJournal-Mastercard Advertorial',
                genre: 'Advertorials', 
                date: '2020-01-15',
                summary: 'Details the anatomy of account takeover attacks, from automated credential stuffing to sophisticated methods that mimic human behavior. It explains how fraudsters leverage stolen data from breaches to seize control of user accounts for financial gain, and outlines the importance of multi-layered security solutions that analyze user behavior to differentiate legitimate customers from criminals.',
                article_url: 'https://www.paymentsjournal.com/the-architecture-of-an-attack-nudata-breaks-down-account-takeover-attacks/',
                tags: ['Fraud Prevention/Detection', 'Emerging Technology', 'Artificial Intelligence', 'Cybersecurity'],
            },
            {
                id: 'bnpl-regulation-is-coming-slowly-april-2023',
                title: 'BNPL Regulation Is Coming Slowly',
                publication: 'PYMNTS-Splitit Buy Now, Pay Later Tracker',
                genre: 'Advertorials',
                date: '2023-04-01',
                summary: 'Explores the growing scrutiny of the Buy Now, Pay Later (BNPL) industry by regulators worldwide. As BNPL use explodes, concerns are rising around consumer debt, overspending, and data privacy, prompting governments in the U.S., U.K., and Australia to consider new rules that would bring BNPL offerings more in line with traditional credit products.',
                tags: ['Traditional & Alternative Credit', 'Rules & Regulations', 'FinTech'],
            },
            {
                id: 'changing-regulatory-landscape-credit-unions-april-2023',
                title: 'Changing Regulatory Landscape Brings Member Focus to Credit Unions',
                publication: 'PYMNTS-PSCU Credit Union Tracker',
                genre: 'Advertorials',
                date: '2023-04-01',
                summary: 'Analyzes the shifting regulatory landscape for credit unions in the wake of recent banking instability. It covers the potential impacts of new rules from the NCUA and CFPB, the looming threat of interchange fee caps, and the need for CUs to proactively engage with legislators while strengthening member-focused services to stay competitive.',
                tags: ['Credit Unions', 'Rules & Regulations', 'Financial Services'],
            },
            {
                id: 'baas-fis-win-customers-march-2023',
                title: 'How BaaS Can Help FIs Win More Customers',
                publication: 'PYMNTS-Galileo Embedded Finance Tracker',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'Examines how Banking as a Service (BaaS) is becoming a critical tool for financial institutions to expand their reach and attract new customers. By partnering with non-bank brands, FIs can embed financial products into third-party platforms, offering everything from payment processing to lending services that meet consumers where they are.',
                tags: [ 'Embedded Finance & BaaS', 'FinTech', 'Mobile Banking', 'Financial Services', 'Emerging Technology'],
            },
            {
                id: 'improving-campus-payments-experience-nov-2022',
                title: 'Improving the Campus Payments Experience',
                publication: 'PYMNTS-American Express B2B and Digital Payments Tracker',
                genre: 'Advertorials',
                date: '2022-11-01',
                summary: 'Details the challenges and opportunities in modernizing campus payment systems. With students expecting seamless, mobile-first experiences, universities are moving away from legacy systems and adopting unified platforms that can handle everything from tuition and dining to event tickets and laundry, often going cashless to improve efficiency and security.',
                tags: ['Emerging Technology', 'Industry-Specific Payment Solutions', 'Digital Payments', 'Customer Experience'],
            },
            {
                id: 'minimizing-subscription-churn-nov-2022',
                title: 'Minimizing Subscription Churn Through Improved Customer Experiences',
                publication: 'PYMNTS-Vindicia Subscription Commerce Tracker',
                genre: 'Advertorials',
                date: '2022-11-01',
                summary: 'Focuses on the strategies subscription-based businesses can use to reduce customer churn in an increasingly competitive market. It highlights the importance of a frictionless customer experience, from easy billing and payment options to personalized content and the ability to pause subscriptions, as key to retaining subscribers.',
                tags: ['Industry-Specific Payment Solutions', 'Digital Payments', 'Customer Experience'],
            },
            {
                id: 'money-mobility-property-managers-feb-2023',
                title: 'Money Mobility Helps Property Managers in a Difficult Economy',
                publication: 'PYMNTS-Ingo Money Money Mobility Tracker',
                genre: 'Advertorials',
                date: '2023-02-01',
                summary: 'Explores how digital payment solutions are helping property managers navigate a difficult economic environment. With rising rents and increasing competition, online platforms that streamline rent collection, vendor payments, and security deposit refunds are essential for improving operational efficiency and tenant satisfaction.',
                tags: ['Digital Payments', 'FinTech', 'Customer Experience', 'Industry-Specific Payment Solutions'],
            },
            {
                id: 'money-mobility-insurance-industry-jan-2023',
                title: 'Money Mobility Comes to the Insurance Industry',
                publication: 'PYMNTS-Ingo Money Money Mobility Tracker',
                genre: 'Advertorials',
                date: '2023-01-01',
                summary: 'Analyzes the insurance industry\'s slow but steady adoption of digital payment solutions. As consumer demand for faster, more convenient claims processing grows, insurers are leveraging money mobility to speed up disbursements, reduce fraud, and improve the overall customer experience in a competitive market.',
                tags: ['Industry-Specific Payment Solutions', 'Digital Payments', 'FinTech'],
            },
            {
                id: 'stopping-bank-fraud-cybersecurity-june-2023',
                title: 'Stopping Bank Fraud With Cybersecurity Solutions',
                publication: 'PYMNTS Digital-First Banking Tracker',
                genre: 'Advertorials',
                date: '2023-06-01',
                summary: 'Outlines the growing threat of bank fraud and the cybersecurity solutions financial institutions are using to combat it. With fraud losses mounting, banks are increasingly turning to advanced technologies like AI, machine learning, and biometric authentication to protect their customers and themselves from sophisticated cyberattacks.',
                tags: ['Fraud Prevention/Detection', 'Cybersecurity', 'Mobile Banking'],
            },
            {
                id: 'core-modernization-cloud-migration-banks-oct-2022',
                title: 'Why Core Modernization And Cloud Migration Matters For Banks',
                publication: 'PYMNTS-Galileo Embedded Finance Tracker',
                genre: 'Advertorials',
                date: '2022-10-01',
                summary: 'Explains why modernizing legacy core banking systems is critical for financial institutions to compete in the digital age. By migrating to the cloud, banks can enable embedded finance solutions, improve operational efficiency, and offer the seamless, personalized experiences that customers now expect. The article also discusses the challenges of cloud migration and the importance of choosing the right partner for a successful transition.',
                tags: ['Emerging Technology', 'Banks & Traditional FIs', 'Embedded Finance & BaaS','Payments Innovation'],
            },
        ];
