const articles = [
            {
                id: 'api-banking-overview-aug-2019',
                title: 'What Are APIs and How Are They Changing Banking?',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-08-13',
                summary: "What Are APIs and How Are They Changing Banking?",
                article_url: 'https://www.paymentsjournal.com/what-are-apis-and-how-are-they-changing-banking/',
                tags: ['APIs', 'Banking', 'Technology'],
            },
            {
                id: 'visa-mastercard-dispute-explainer-nov-2019',
                title: 'Visa and Mastercard Changed Their Dispute Resolution Process. Here’s What You Need to Know',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-11-13',
                summary: 'Add me later!',
                article_url: 'https://www.paymentsjournal.com/visa-and-mastercard-changed-their-dispute-resolution-process-heres-what-you-need-to-know/',
                tags: ['Credit', 'Credit Cards'],
            },
            {
                id: 'fed-real-time-payment-announcement-news-aug-2019',
                title: 'Fed to Create Real-Time Payments Network',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-08-05',
                summary: 'Add later!!',
                article_url: 'https://www.paymentsjournal.com/fed-to-create-real-time-payment-network/',
                tags: ['Real-time Payments', 'Payments Innovation'],
            },
            {
                id: 'visa-combatting-fraud-news-jun-2019',
                title: 'Using Artificial Intelligence, Visa Is Combatting Fraud at Nearly the Speed of Light',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-06-17',
                summary: "Explains how Visa’s AI-powered system, Visa Advanced Authorization (VAA), reviews every transaction on VisaNet in about one millisecond—analyzing over 500 risk signals to differentiate fraud from good behavior. This ultra-fast risk scoring helps issuers stop roughly $25 billion in fraud annually without slowing down customers or triggering false declines..",
                article_url: 'https://www.paymentsjournal.com/using-artificial-intelligence-visa-is-combatting-fraud-at-nearly-the-speed-of-light/',
                tags: ['Fraud', 'Artificial Intelligence', 'Digital Security', 'Emerging Technology'],
            },

            {
                id: 'fintech-bubble-profitability-mar-2023',
                title: 'The Bursting FinTech Bubble Places Primacy on Profitability',
                publication: 'PYMNTS FinTech Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'An analysis of the significant shift in the FinTech landscape, where economic headwinds and market corrections are forcing companies, especially in the BNPL sector, to move beyond growth-at-all-costs and focus intensely on achieving sustainable profitability.',
                tags: ['FinTech', 'BNPL', 'Profitability'],
            },
            {
                id: 'verify-account-identity',
                title: 'Verifying Account Identity in the Age of Real-Time Payments',
                publication: 'PaymentsJournal Article',
                employer: 'PaymentsJournal',
                genre: 'Advertorials',
                date: '2019-10-02',
                summary: 'Account validation is more important than ever in an age of real-time payments. Merchants need the proper technology in place to protect themselves.',
                article_url: 'https://www.paymentsjournal.com/verifying-account-identity-in-the-age-of-real-time-payments/',
                tags: ['Fraud', 'Digital Security', 'Artificial Intelligence', 'Emerging Technology'],
            },
            {
                id: 'fintech-bank-collaboration-jun-2023',
                title: 'The FinTech-Bank Relationship Shifts Toward Collaboration',
                publication: 'PYMNTS FinTech Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-06-01',
                summary: 'Examines the evolving dynamic between traditional financial institutions and FinTechs, highlighting a strategic move from competition to collaboration. This shift is driven by digital transformation, open banking regulations, and shared security concerns.',
                tags: ['FinTech', 'Banking', 'Embedded Finance & BaaS', 'Emerging Technology'],
            },
             {
                id: 'credit-book-report-mercator-research-mar-2021',
                title: 'The 2021 Credit Card Data Book Part One: Internal Dynamics',
                publication: 'Mercator Advisory Group',
                employer: 'Mercator',
                genre: 'Research',
                date: '2021-03-30',
                summary: 'A deep dive into the state of the credit industry during COVID and.......',
                article_url: 'https://javelinstrategy.com/research/2021-credit-card-data-book-part-one-internal-dynamics/',
                tags: ['Credit Cards', 'Lending', 'Banking'],
            },
            {
                id: 'fintech-lending-access-may-2023',
                title: "FinTechs' Role in Improving Access to Lending Services",
                publication: 'PYMNTS FinTech Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-05-01',
                summary: 'Explores how FinTech innovations and alternative credit models, such as BNPL, are providing crucial access to lending services for consumers who may be underserved by traditional credit scoring systems, thereby promoting financial inclusion.',
                tags: ['FinTech', 'Lending', 'Credit', 'BNPL'],
            },
            {
                id: 'restaurants-technology-inflation-jun-2023',
                title: 'Inflation Puts Technology on the Menu for Restaurants',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-06-01',
                summary: 'Details how restaurants are increasingly adopting automation, digital payment systems, and other technologies to combat the dual pressures of rising inflation and persistent labor shortages, fundamentally changing their operational models.',
                tags: ['Payments', 'Industry-Specific Payment Solutions', 'Digital Payments', 'Technology'],
            },
            {
                id: 'consumer-covid-response-news-mar-2020',
                title: 'Here\’s How Consumers are Responding to COVID-19',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2020-03-31',
                summary: 'Shares early research on how the pandemic reshaped consumer habits, from increased online grocery shopping and food delivery to greater use of contactless payments. Highlights lasting shifts toward digital convenience as businesses adjusted to closures, service cuts, and staff reductions.',
                article_url: 'https://www.paymentsjournal.com/heres-how-consumers-are-responding-to-covid-19/',
                tags: ['Payments', 'Consumer Behavior', 'B'],
            },
            {
                id: 'beauty-wellness-transformation-may-2023',
                title: 'The Digital Transformation of Beauty and Wellness Services',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-05-01',
                summary: 'Analyzes the rapid adoption of digital tools within the beauty and wellness industry, from online booking and integrated payment systems to "treat now, pay later" financing, showcasing a sector-wide move towards a seamless, tech-driven customer experience.',
                tags: ['SMB', 'Customer Experience', 'Emerging Technology','Industry-Specific Payment Solutions'],
            },
            {
                id: 'smb-fraud-threats-remote-work-mar-2023',
                title: 'How SMBs Can Fight the Fraud Threats of Remote Work',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'An exploration of the heightened fraud and security risks for SMBs due to the rise of remote work. It focuses on payment fraud, business email compromise (BEC), and actionable strategies for defense in a decentralized work environment.',
                tags: ['SMB', 'Fraud', 'Digital Security', 'B2B Payments'],
            },
            {
                id: 'healthcare-payments-improvements-jun-2023',
                title: 'The Healthcare Industry Needs a Dose of Money Mobility',
                publication: 'PYMNTS Money Mobility Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-01-15',
                summary: 'Investigates the pain points in the healthcare payments ecosystem and how innovation can improve the experience.',
                tags: ['Industry-Specific Payment Solutions', 'Cash Flow', 'Digital Payments', 'Consumer Behavior'],
            },
            {
                id: 'smb-retail-payments-jan-2023',
                title: 'Tapping The Payments Opportunity In SMB Retail',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-01-01',
                summary: 'Highlights the significant opportunity for small and mid-sized retailers to drive growth and customer loyalty by adopting modern, flexible payment options that meet evolving consumer preferences for digital and contactless transactions.',
                tags: ['SMB', 'Retail', 'Payments', 'Digital Payments'],
            },
            {
                id: 'smb-cash-flow-2023-nov-dec-2022',
                title: "Improving SMBs' Cash Flow Management In 2023",
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2022-11-15',
                summary: 'A forward-looking piece on the critical nature of cash flow management for SMBs entering 2023. It discusses how technology and strategic partnerships can help businesses navigate economic uncertainty and late payment challenges.',
                tags: ['SMB', 'B2B Payments', 'Technology'],
            },
             {
                id: 'nonfinancial-brands-embedded-finance-april-2023',
                title: 'How Nonfinancial Brands Can Benefit From Embedded Finance',
                publication: 'Embedded Finance Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-04-01',
                summary: "A look at how nonfinancial brands can use embedded finance and BaaS to meet their customer's payments needs.",
                tags: ['SMB', 'B2B Payments', 'Emerging Technology', 'Embedded Finance & BaaS'],
            },
            {
                id: 'big-tech-is-coming-dec-2019',
                title: 'Hey Issuers, Big Tech Is Coming. Here’s How to Compete',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'Advertorial',
                date: '2019-12-04',
                summary: 'Explores how Apple’s launch of the Apple Card—with its slick app, seamless onboarding, no fees, and ecosystem-driven rewards—is pushing traditional card issuers to rethink their strategies by focusing squarely on superior customer experience and digital-first design.',
                article_url: 'https://www.paymentsjournal.com/hey-issuers-big-tech-is-coming-heres-how-to-compete/',
                tags: ['FinTech', 'Mobile Banking', 'Consumer Behavior', 'Payments Innovation'],
            },
            {
                id: 'improving-customer-experience-oct-2019',
                title: 'Improving Customer Experience in the Moments That Matter',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'Advertorial',
                date: '2019-10-22',
                summary: 'Highlights how financial institutions can seize high-stress customer touchpoints—like lost or compromised cards—to strengthen loyalty. Featuring insights from Mercator Advisory Group, the piece shows how mobile apps can streamline card shutdowns, real-time charge tracking, and clear alerts.',
                article_url: 'https://www.paymentsjournal.com/improving-customer-experience-in-the-moments-that-matter/',
                tags: ['Banking', 'FinTech', 'Customer Experience', 'Consumer Behavior', 'Mobile Banking'],
            },
            {
                id: 'connected-intelligence-fighting-fraud-july-2019',
                title: 'Connected Intelligence: A Holistic Approach to Fighting Fraud',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'Advertorial',
                date: '2019-07-18',
                summary: 'This outline Mastercard\'s cutting-edge methods for fighting fraud——ditching passwords-only security in favor of real-time, layered authentication. It weaves together biometrics, device fingerprinting, behavioral profiling, location, and machine learning across the entire user journey. This lets companies flag fraudulent activity pre-transaction, minimize friction through smarter risk scoring, and reduce false positives while stopping fraud before it begins.',
                article_url: 'https://www.paymentsjournal.com/connected-intelligence-a-holistic-approach-to-fighting-fraud/',
                tags: ['Fraud', 'Artificial Intelligence', 'Digital Security', 'Emerging Technology'],
            },
            {
                id: 'understanding-synthetic-identity-fraud-aug-2019',
                title: 'Understanding and Stopping Synthetic Identity Fraud',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'Advertorial',
                date: '2019-08-01',
                summary: 'Exposes how fraudsters mix stolen Social Security numbers with made-up names and details to create “synthetic identities” that behave like model borrowers—until they don’t. And explores how companies can fight back.',
                article_url: 'https://www.paymentsjournal.com/understanding-and-stopping-synthetic-identity-fraud/',
                tags: ['Fraud', 'Digital Security', 'Artificial Intelligence', 'Emerging Technology'],
            }
        ];