const articles = [
            {
                id: 'api-banking-overview-aug-2019',
                title: 'What Are APIs and How Are They Changing Banking?',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-08-13',
                summary: "What Are APIs and How Are They Changing Banking?",
                article_url: 'https://www.paymentsjournal.com/what-are-apis-and-how-are-they-changing-banking/',
                tags: ['APIs', 'Banking', 'Technology'],
            },
            {
                id: 'visa-mastercard-dispute-explainer-nov-2019',
                title: 'Visa and Mastercard Changed Their Dispute Resolution Process. Here’s What You Need to Know',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-11-13',
                summary: 'Add me later!',
                article_url: 'https://www.paymentsjournal.com/visa-and-mastercard-changed-their-dispute-resolution-process-heres-what-you-need-to-know/',
                tags: ['Credit', 'Credit Cards'],
            },
            {
                id: 'fed-real-time-payment-announcement-news-aug-2019',
                title: 'Fed to Create Real-Time Payments Network',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-8-5',
                summary: 'Add later!!',
                article_url: 'https://www.paymentsjournal.com/fed-to-create-real-time-payment-network/',
                tags: ['real-time payments', 'payments innovation'],
            },
            {
                id: 'visa-combatting-fraud-news-jun-2019',
                title: 'Using Artificial Intelligence, Visa Is Combatting Fraud at Nearly the Speed of Light',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2019-06-17',
                summary: "A brief dive into Visa's cutting-edge efforts to detect and prevent fraud.",
                article_url: 'https://www.paymentsjournal.com/using-artificial-intelligence-visa-is-combatting-fraud-at-nearly-the-speed-of-light/',
                tags: ['Fraud', 'Artificial Intelligence', 'Digital Security', 'Emerging Technology'],
            },

            {
                id: 'fintech-bubble-profitability-mar-2023',
                title: 'The Bursting FinTech Bubble Places Primacy on Profitability',
                publication: 'PYMNTS FinTech Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'An analysis of the significant shift in the FinTech landscape, where economic headwinds and market corrections are forcing companies, especially in the BNPL sector, to move beyond growth-at-all-costs and focus intensely on achieving sustainable profitability.',
                tags: ['FinTech', 'BNPL', 'Profitability'],
            },
            {
                id: 'verify-account-identity',
                title: 'Verifying Account Identity in the Age of Real-Time Payments',
                publication: 'PaymentsJournal Article',
                employer: 'PaymentsJournal',
                genre: 'Advertorials',
                date: '2019-10-02',
                summary: 'Account validation is more important than ever in an age of real-time payments. Merchants need the proper technology in place to protect themselves.',
                // Kept because it's an external link
                article_url: 'https://www.paymentsjournal.com/verifying-account-identity-in-the-age-of-real-time-payments/',
                tags: ['Fraud'],
            },
            {
                id: 'fintech-bank-collaboration-jun-2023',
                title: 'The FinTech-Bank Relationship Shifts Toward Collaboration',
                publication: 'PYMNTS FinTech Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-06-01',
                summary: 'Examines the evolving dynamic between traditional financial institutions and FinTechs, highlighting a strategic move from competition to collaboration. This shift is driven by digital transformation, open banking regulations, and shared security concerns.',
                tags: ['FinTech', 'Banking', 'Open Banking'],
            },
             {
                id: 'credit-book-report-mercator-research-mar-2021',
                title: 'The 2021 Credit Card Data Book Part One: Internal Dynamics',
                publication: 'Mercator Advisory Group',
                employer: 'Mercator',
                genre: 'Research',
                date: '2021-03-30',
                summary: 'A deep dive into the state of the credit industry during COVID and.......',
                article_url: 'https://javelinstrategy.com/research/2021-credit-card-data-book-part-one-internal-dynamics/',
                tags: ['Credit Cards', 'Lending', 'Banking'],
            },
            {
                id: 'fintech-lending-access-may-2023',
                title: "FinTechs' Role in Improving Access to Lending Services",
                publication: 'PYMNTS FinTech Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-05-01',
                summary: 'Explores how FinTech innovations and alternative credit models, such as BNPL, are providing crucial access to lending services for consumers who may be underserved by traditional credit scoring systems, thereby promoting financial inclusion.',
                tags: ['FinTech', 'Lending', 'Credit', 'BNPL'],
            },
            {
                id: 'restaurants-technology-inflation-jun-2023',
                title: 'Inflation Puts Technology on the Menu for Restaurants',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-06-01',
                summary: 'Details how restaurants are increasingly adopting automation, digital payment systems, and other technologies to combat the dual pressures of rising inflation and persistent labor shortages, fundamentally changing their operational models.',
                tags: ['B2B Payments', 'Restaurants', 'Automation', 'Technology'],
            },
            {
                id: 'consumer-covid-response-news-mar-2020',
                title: 'Here\’s How Consumers are Responding to COVID-19',
                publication: 'PaymentsJournal',
                employer: 'PaymentsJournal',
                genre: 'News & Analysis',
                date: '2020-3-31',
                summary: 'Add!.',
                // Kept because these are placeholder links
                article_url: 'https://www.paymentsjournal.com/heres-how-consumers-are-responding-to-covid-19/',
                tags: ['B2B Payments', 'Working Capital', 'Cash Flow', 'SMB'],
            },
            {
                id: 'beauty-wellness-transformation-may-2023',
                title: 'The Digital Transformation of Beauty and Wellness Services',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-05-01',
                summary: 'Analyzes the rapid adoption of digital tools within the beauty and wellness industry, from online booking and integrated payment systems to "treat now, pay later" financing, showcasing a sector-wide move towards a seamless, tech-driven customer experience.',
                tags: ['B2B Payments', 'Digital Transformation', 'SMB', 'Customer Experience', 'Industry-Specific Payment Solutions'],
            },
            {
                id: 'smb-fraud-threats-remote-work-mar-2023',
                title: 'How SMBs Can Fight the Fraud Threats of Remote Work',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-03-01',
                summary: 'An exploration of the heightened fraud and security risks for SMBs due to the rise of remote work. It focuses on payment fraud, business email compromise (BEC), and actionable strategies for defense in a decentralized work environment.',
                tags: ['SMB', 'Fraud', 'Security', 'Remote Work', 'B2B Payments'],
            },
            {
                id: 'healthcare-payments-improvements-jun-2023',
                title: 'The Healthcare Industry Needs a Dose of Money Mobility',
                publication: 'PYMNTS Money Mobility Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-01-15',
                summary: 'Investigates the pain points in the healthcare payments ecosystem and how innovation can improve the experience.',
                tags: ['Industry-Specific Payment Solutions', 'Healthcare', 'Cash Flow', 'Digital Payments', 'Customer Experience'],
            },
            {
                id: 'smb-retail-payments-jan-2023',
                title: 'Tapping The Payments Opportunity In SMB Retail',
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-01-01',
                summary: 'Highlights the significant opportunity for small and mid-sized retailers to drive growth and customer loyalty by adopting modern, flexible payment options that meet evolving consumer preferences for digital and contactless transactions.',
                tags: ['SMB', 'Retail', 'Payments', 'Digital Payments'],
            },
            {
                id: 'smb-cash-flow-2023-nov-dec-2022',
                title: "Improving SMBs' Cash Flow Management In 2023",
                publication: 'PYMNTS B2B and Digital Payments Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2022-11-15',
                summary: 'A forward-looking piece on the critical nature of cash flow management for SMBs entering 2023. It discusses how technology and strategic partnerships can help businesses navigate economic uncertainty and late payment challenges.',
                tags: ['SMB', 'Cash Flow', 'B2B Payments', '2023 Outlook'],
            },
             {
                id: 'nonfinancial-brands-embedded-finance-april-2023',
                title: 'How Nonfinancial Brands Can Benefit From Embedded Finance',
                publication: 'Embedded Finance Tracker',
                employer: 'PYMNTS',
                genre: 'Advertorials',
                date: '2023-04-01',
                summary: "A look at how nonfinancial brands can use embedded finance and BaaS to meet their customer's payments needs.",
                tags: ['SMB', 'Cash Flow', 'B2B Payments', 'embedded finance'],
            }
        ];